# Generated by Django 4.0.8 on 2023-06-14 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('it_infrastructure', models.CharField(max_length=100)),
                ('storage_n_backup', models.CharField(max_length=100)),
                ('cctv_surveillance', models.CharField(max_length=100)),
                ('civil_works', models.CharField(max_length=100)),
                ('application_n_platforms', models.CharField(max_length=100)),
                ('cybersecurity_n_network', models.CharField(max_length=100)),
                ('cloud_n_virtualization_services', models.CharField(max_length=100)),
                ('Electrical_works', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
