# Generated by Django 4.0.8 on 2023-06-21 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Engineering',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('civil_engineering', models.CharField(max_length=100)),
                ('mechanical_engineering', models.CharField(max_length=100)),
                ('electrical_engineering', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('government_enterprises', models.CharField(max_length=100)),
                ('hospitality_info', models.CharField(max_length=100)),
                ('production_of_goods', models.CharField(max_length=100)),
                ('telecommunications', models.CharField(max_length=100)),
                ('building_construction', models.CharField(max_length=100)),
                ('power_n_energy', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('registered_offices', models.CharField(max_length=100)),
                ('corporate_offices', models.CharField(max_length=100)),
                ('other_offices', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('hmis', models.CharField(max_length=100)),
                ('video_kyc', models.CharField(max_length=100)),
                ('voice_bot', models.CharField(max_length=100)),
                ('quality_control_work_monitoring_system', models.CharField(max_length=100)),
                ('gpc_based_attendance_monitoring_system', models.CharField(max_length=100)),
                ('restaurant_portal', models.CharField(max_length=100)),
                ('finance_portal', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dept_type',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('engg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.engineering')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
