# Generated by Django 4.0.8 on 2023-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_us_engineering_industries_offices_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='finance_portal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gpc_based_attendance_monitoring_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hmis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality_control_work_monitoring_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='restaurant_portal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_kyc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
