# Generated by Django 4.0.8 on 2023-06-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_finance_portal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_type',
            name='engg',
            field=models.CharField(choices=[('civil_engineering', 'civil_engineering'), ('mechanical_engineering', 'mechanical_engineering'), ('electrical_engineering', 'electrical_engineering')], max_length=500),
        ),
    ]
