# Generated by Django 4.0.8 on 2023-06-22 06:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_dept_type_engg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Sales', 'Sales'), ('Accountant', 'Accountant')], max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_description', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dept_type',
            name='engg',
            field=models.CharField(choices=[('civil_engineering', 'civil_engineering'), ('mechanical_engineering', 'mechanical_engineering'), ('electrical_engineering', 'electrical_engineering')], max_length=100),
        ),
    ]
