# Generated by Django 4.0.8 on 2023-06-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_career_alter_dept_type_engg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engineering',
        ),
    ]
