# Generated by Django 4.0.8 on 2023-06-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_engineering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offices',
            name='corporate_offices',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='other_offices',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='registered_offices',
        ),
        migrations.AddField(
            model_name='offices',
            name='address',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offices',
            name='office_choices',
            field=models.CharField(choices=[('registered_offices', 'registered_offices'), ('corporate_offices', 'corporate_offices'), ('other_offices', 'other_offices')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
