# Generated by Django 4.0.8 on 2023-06-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_offices_corporate_offices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='finance_portal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gpc_based_attendance_monitoring_system',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hmis',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality_control_work_monitoring_system',
        ),
        migrations.RemoveField(
            model_name='product',
            name='restaurant_portal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video_kyc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='voice_bot',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_choices',
            field=models.CharField(choices=[('hms', 'hms'), ('video_kyc', 'video_kyc'), ('voice_bot', 'voice_bot'), ('quality_control_work_monitoring_system', 'quality_control_work_monitoring_system'), ('gpc_based_attendance_monitoring_system', 'gpc_based_attendance_monitoring_system'), ('restaurant_portal', 'restaurant_portal'), ('finance_portal', 'finance_portal')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
